# Generated by Django 4.0.4 on 2023-04-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0002_delete_userotp_alter_applications_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvocateEntries',
        ),
    ]
