# Generated by Django 4.0.4 on 2023-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0003_delete_advocateentries'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='pages',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
