# Generated by Django 4.0.4 on 2023-04-15 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default=None, max_length=10, unique=True)),
                ('otp', models.CharField(default=None, max_length=6)),
                ('opt_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default=None, max_length=120)),
                ('contact_number', models.CharField(default=None, max_length=10, unique=True)),
                ('email', models.EmailField(default=None, max_length=100, null=True)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=128, null=True)),
                ('photo', models.CharField(default=None, max_length=100, null=True)),
                ('id_proof', models.CharField(default=None, max_length=100, null=True)),
                ('bar_registration_number', models.CharField(default=None, max_length=30, null=True)),
                ('bar_certificate', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
