# Generated by Django 4.0.4 on 2023-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(default=None, max_length=100)),
                ('adv_reg', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=254, null=True)),
                ('email', models.CharField(default=None, max_length=254, null=True)),
                ('adv_mobile', models.CharField(default=None, max_length=15)),
                ('adv_gender', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
