# Generated by Django 4.0.4 on 2023-06-05 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='account.organisation'),
        ),
    ]
