# Generated by Django 4.0.4 on 2023-06-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Organisation',
            new_name='organisation',
        ),
    ]
