# Generated by Django 4.0.4 on 2023-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
