# Generated by Django 4.0.4 on 2023-06-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0014_alter_applicationforwardeddetails_forwarded_to'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
