# Generated by Django 4.0.4 on 2023-06-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=20, unique=True)),
                ('cnr', models.CharField(max_length=30)),
                ('first_petitioner', models.CharField(max_length=128)),
                ('first_respondent', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default=None, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=512, null=True)),
                ('document', models.CharField(max_length=256, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIndexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256)),
                ('page', models.BigIntegerField(default=None)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.documents')),
            ],
        ),
        migrations.CreateModel(
            name='CauseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_s_no', models.CharField(max_length=5)),
                ('display_name', models.CharField(max_length=2048, null=True)),
                ('date', models.DateField(default=None)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.CharField(default=None, max_length=3)),
                ('bookmark_label', models.CharField(default=None, max_length=255, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsel_name', models.CharField(max_length=128, null=True)),
                ('counsel_for', models.CharField(max_length=2, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(max_length=2, null=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperless_court.casedetails')),
            ],
        ),
    ]
