# Generated by Django 4.0.4 on 2023-04-17 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='ducement_url',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupportingDocument',
        ),
    ]
