# Generated by Django 4.0.4 on 2023-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0002_application_document_name_application_ducement_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_id',
            new_name='application_no',
        ),
        migrations.AlterField(
            model_name='application',
            name='ducement_url',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
