# Generated by Django 4.0.4 on 2023-04-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0003_rename_application_id_application_application_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ducement_url',
            new_name='document_url',
        ),
    ]
