# Generated by Django 4.0.4 on 2023-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0005_application_mailing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='economic_category',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='economic_category_proof_url',
            field=models.FileField(blank=True, null=True, upload_to='RTI/2023'),
        ),
        migrations.AlterField(
            model_name='application',
            name='content',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_url',
            field=models.FileField(blank=True, null=True, upload_to='RTI/2023'),
        ),
    ]
