# Generated by Django 4.0.4 on 2023-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0006_application_economic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='economic_category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
