# Generated by Django 4.0.4 on 2023-05-30 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rti', '0006_application_economic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='economic_category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationForwardedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarded_to', models.CharField(max_length=1028)),
                ('forwarded_on', models.DateField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forwarded_details', to='rti.application')),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forwarded_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
