# Generated by Django 4.0.4 on 2023-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0007_alter_application_economic_category'),
        ('rti', '0007_alter_application_economic_category_and_more'),
    ]

    operations = [
    ]
