# Generated by Django 4.0.4 on 2023-05-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0008_merge_20230530_0629'),
        ('rti', '0009_application_applied_on_and_more'),
    ]

    operations = [
    ]
