# Generated by Django 4.0.4 on 2023-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0010_merge_20230531_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='received_on',
            field=models.DateField(null=True),
        ),
    ]
