# Generated by Django 4.0.4 on 2023-06-01 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('rti', '0011_alter_application_received_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationforwardeddetails',
            name='forwarded_to_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=1028),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationforwardeddetails',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.organisation'),
        ),
    ]
