# Generated by Django 4.0.4 on 2023-06-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('rti', '0012_applicationforwardeddetails_forwarded_to_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationforwardeddetails',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forwarded_details', to='common.organisation'),
        ),
    ]
