# Generated by Django 4.0.4 on 2023-06-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organisation'),
        ('rti', '0013_application_deadline_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationforwardeddetails',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forwarded_details', to='account.organisation'),
        ),
    ]
