# Generated by Django 4.0.4 on 2023-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0014_alter_applicationforwardeddetails_forwarded_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_completed_by_hc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationforwardeddetails',
            name='remarks',
            field=models.CharField(default='', max_length=512),
        ),
    ]
